### ISSUE TITLE
Fix @-sign spacing

### ISSUE THREAD

**Issue by href** [seantis/lektor-seantis-website#9]
This should probably be the same as the phone:
![screenshot of safari 30-09-16 15-37-13](https://cloud.githubusercontent.com/assets/273163/18993493/cfe10ec6-8723-11e6-8a52-d7a0409484fd.png)

Also, there's a space missing between CH-6004 and Luzern.

**Comment by treinhard** [comment]
Whitespace missing between zip and city too.

**Comment by freinhard** [comment]
Fixed with bdb2971a
